service: crud-backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    STAGE: ${self:provider.stage}

plugins:
  - serverless-plugin-typescript
  - serverless-offline

defaults:
  function:
    timeout: 10

functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /hello
          method: get
          cors: true
