name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

permissions:
  checks: write
  contents: write
  pull-requests: write

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Use Node.js 18
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Audit for vulnerabilities
        run: npm audit --production

      - name: Lint
        run: npm run lint

      - name: Type Check
        run: npx tsc --noEmit

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Report coverage
        uses: ArtiomTr/jest-coverage-report-action@v2.3.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          threshold: 70
