name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request_target:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

permissions:
  checks: write
  pull-requests: write
  contents: write

jobs:
  validate:
    if: github.actor != 'release-please[bot]'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Audit for vulnerabilities
        run: npm audit --production

      - name: Lint
        run: npm run lint

      - name: Type Check
        run: npx tsc --noEmit

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Report coverage
        uses: ArtiomTr/jest-coverage-report-action@v2.3.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          threshold: 70
