name: Deploy to AWS

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed

permissions:
  id-token: write
  contents: read

jobs:
  deploy-dev:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'develop' }}
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/setup.yml
        with:
          node-version: '18'

      - name: Deploy to dev
        run: npx serverless deploy --stage dev

  deploy-prod:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: ./.github/workflows/setup.yml
        with:
          node-version: '18'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: sa-east-1

      - name: Deploy to prod
        run: npx serverless deploy --stage prod
