name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create release PR
    runs-on: ubuntu-latest
    steps:
      - name: Run release-please
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: node
          package-name: crud-backend
