name: Reusable Setup

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v4.0.3
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
